### ISSUE TITLE
Boundary 문제

### ISSUE THREAD

**Issue by insooneelife** [Realtrick-Games/DeadForest#71]
Entity가 boundary를 넘어갈 경우 게임이 터진다.
Graph 탐색 시 boundary를 넘겨서 탐색을 하는 시나리오가 발생할 수 있다.
두 문제를 동시에 해결하기 위해 사각형 dummy structure 4개를 생성하여,
entity가 boundary 밖으로 나가지 못하게 하고, graph 또한 생성 과정에서 밖으로의 edge를 생성하지 않도록 하여 해결한다.

**Comment by njh0602** [comment]
일단 언덕 두르고 진행 (개구멍 하나 만들어야댐)
